version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  verify_code:
    jobs:
      - build_test_lint

jobs:
  build_test_lint: 
    executor: node/default 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn lint:ci
          name: Verify lint
      - run:
          command: yarn build
          name: Build app