version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  verify_code:
    jobs:
      - build_install_packages:
      - test:
          requires:
            - build_install_packages
      - verify_lint:
          requires:
            - test

jobs:
  build_install_packages:
    executor: node/default
    steps: 
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test:
    executor: node/default
    steps:
      - run:
          command: yarn test
          name: Run tests
  verify_lint:
    executor: node/default
    steps:
      - run:
          command: yarn lint:ci
          name: Verify lint