version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  verify_code:
    jobs:
      - verify_lint
      - test:
          requires:
            - verify_lint
      - build:
          requires:
            - test

jobs:
  build:
    executor: node/default
    steps: 
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
          name: Build app
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
  verify_lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - checkout
      - run:
          command: yarn lint:ci
          name: Verify lint