version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  test-and-verify-lint:
    jobs:
      - checkout
      - run:
          name: Run tests
          command: yarn:test
      - run:
        name: Run lint
        command: yarn lint:ci
        
      
      