version: 2.1

orbs:
  node: circleci/node@5.0.2

workflows:
  verify_code:
    jobs:
      - install_packages
      - build
        requires:
          - install_packages
      - test
        requires:
          - build
      - verify_lint
        requires:
          - test

jobs:
  install_packages:
    executor: node/default
    steps: 
      - checkout
      - node/install-packages:
          pkg-manager: yarn
  build:
    executor: node/default
    steps:
      -run:
        command: yarn build
        name: Build app
  test:
    executor: node/default
    steps:
      -run:
        command: yarn test
        name: Run tests
  verify_lint
    executor: node/default
    steps:
      -run:
        command: yarn lint:ci
        name: Verify lint
      
