version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test_and_lint: 
    executor: node/default 
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn lint:ci
          name: Verify lint
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: .